//
//  GenresModuleConfigurator.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import UIKit

class GenresModuleConfigurator
{
    class func configureModule() -> UIViewController
    {
        let viewController = GenresViewController.instantiate()
        let presenter: GenresPresenterProtocol & GenresInteractorOutputProtocol = GenresPresenter()
        let interactor: GenresInteractorInputProtocol = GenresInteractor()
        let dataService: LibraryServiceProtocol = LibraryService()
        let wireFrame: GenresWireframeProtocol = GenresWireframe()
        
        viewController.presenter = presenter
        presenter.view = viewController
        presenter.wireFrame = wireFrame
        presenter.interactor = interactor
        interactor.presenter = presenter
        interactor.dataService = dataService
        
        return viewController
    }
}
