//
//  BooksWireframe.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import UIKit

class BooksWireframe: BooksWireframeProtocol
{
    
}
