//
//  GenresWireframe.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import UIKit

class GenresWireframe: GenresWireframeProtocol
{
    func showBooks(from view: GenresViewControllerProtocol?, for genre: Genre)
    {
        guard let sourceView = view as? UIViewController else
        {
            return
        }
        let booksViewController = BooksModuleConfigurator.configureModule(with: genre)
        sourceView.navigationController?.pushViewController(booksViewController, animated: true)
    }
}
