//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Unidirectional VIPER, generated by the ♻️ RMVIPER generator
//

import Foundation

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorProtocol
{
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?
    
}
