//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Unidirectional VIPER, generated by the ♻️ RMVIPER generator
//

import UIKit

// INTERACTOR
protocol ___VARIABLE_productName:identifier___InteractorProtocol: class
{
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol? { get set }
    
    // VIEW -> INTERACTOR
    
}

// PRESENTER
protocol ___VARIABLE_productName:identifier___PresenterProtocol: class
{
    var view: ___VARIABLE_productName:identifier___ViewControllerProtocol? { get set }
    var wireFrame: ___VARIABLE_productName:identifier___WireframeProtocol? { get set }
    
    // INTERACTOR -> PRESENTER
    
}

// VIEW
protocol ___VARIABLE_productName:identifier___ViewControllerProtocol: UIViewController
{
    var interactor: ___VARIABLE_productName:identifier___InteractorProtocol? { get set }
    
    // PRESENTER -> VIEW
    
}

// WIREFRAME
protocol ___VARIABLE_productName:identifier___WireframeProtocol: class
{
    
}
