//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Unidirectional VIPER, generated by the ♻️ RMVIPER generator
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController, Instantiable
{
    var interactor: ___VARIABLE_productName:identifier___InteractorProtocol?
}

// MARK: - Presenter Output
extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewControllerProtocol
{
    
}
