//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import UIKit

// PRESENTER -> VIEW
protocol ___VARIABLE_productName:identifier___ViewControllerProtocol: UIViewController
{
    
}

// PRESENTER -> INTERACTOR
protocol ___VARIABLE_productName:identifier___InteractorInputProtocol: AnyObject
{
    
}

// INTERACTOR -> PRESENTER
protocol ___VARIABLE_productName:identifier___InteractorOutputProtocol: AnyObject
{
    
}

// VIEW -> PRESENTER
protocol ___VARIABLE_productName:identifier___PresenterProtocol: AnyObject
{
    
}

// PRESENTER -> ROUTER
protocol ___VARIABLE_productName:identifier___WireframeProtocol: AnyObject
{
    
}
