//
//  BooksModuleConfigurator.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import UIKit

class BooksModuleConfigurator
{
    class func configureModule(with genre: Genre) -> UIViewController
    {
        let viewController = BooksViewController.instantiate()
        let presenter: BooksPresenterProtocol & BooksInteractorOutputProtocol = BooksPresenter()
        let interactor: BooksInteractorInputProtocol = BooksInteractor()
        let wireFrame: BooksWireframeProtocol = BooksWireframe()
        
        viewController.presenter = presenter
        presenter.view = viewController
        presenter.wireFrame = wireFrame
        presenter.interactor = interactor
        presenter.genre = genre
        interactor.presenter = presenter
        
        return viewController
    }
}
