//
//  GenresViewController.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import UIKit

class GenresViewController: RefreshableViewController, StoryboardInstantiable
{
    static var storyboardName: String = "Genres"
    var presenter: GenresPresenterProtocol?
    
    // MARK: Outlets
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: Life Cycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        presenter?.viewDidLoad()
    }
    
    override func refresh()
    {
        super.refresh()
        presenter?.refreshAllData()
    }
}

// MARK: Presenter Output
extension GenresViewController: GenresViewControllerProtocol
{
    func setupView()
    {
        tableView.hideEmptyCells()
        addRefreshControl(to: tableView)
    }
    
    func reloadData()
    {
        tableView.reloadData()
    }
    
    func showLoading()
    {
        startRefreshAnimation()
    }
    
    func hideLoading()
    {
        stopRefreshAnimation()
    }
    
    func showError(_ error: ErrorType)
    {
        showBannerAlert(title: "Warning", message: error.errorDescription, style: .danger)
    }
}

// MARK: UITableViewDataSource
extension GenresViewController: UITableViewDataSource
{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
    {
        return presenter?.numberOfCells() ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let cell: GenreCell = tableView.dequeueReusableCell(for: indexPath)
        if let cellModel = presenter?.cellViewModel(index: indexPath)
        {
            cell.setupGenre(cellModel)
        }
        return cell
    }
}

// MARK: UITableViewDelegate
extension GenresViewController: UITableViewDelegate
{
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
    {
        presenter?.didSelectCell(index: indexPath)
        tableView.deselectRow(at: indexPath, animated: true)
    }
}
