//
//  BooksInteractor.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import Foundation

class BooksInteractor: BooksInteractorInputProtocol
{
    weak var presenter: BooksInteractorOutputProtocol?
    
}
