//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import Foundation

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___PresenterProtocol
{
    weak var view: ___VARIABLE_productName:identifier___ViewControllerProtocol?
    var interactor: ___VARIABLE_productName:identifier___InteractorInputProtocol?
    var wireFrame: ___VARIABLE_productName:identifier___WireframeProtocol?
    
}

// MARK: - Interactor Output
extension ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol
{
    
}
