//
//  GenresInteractor.swift
//  VIPERSample
//
//  Created User on 9/3/19.
//  Copyright © 2019 User. All rights reserved.
//
//  This file was generated by the ♻️ RMVIPER generator
//

import Foundation

class GenresInteractor: GenresInteractorInputProtocol
{
    weak var presenter: GenresInteractorOutputProtocol?
    var dataService: LibraryServiceProtocol?
    
    func retrieveGenres()
    {
        dataService?.retrieveGenres(onSuccess: { [weak self] genres in
            
            self?.presenter?.didRetrieveGenres(genres)
        }, onFailure: { [weak self] error in
            self?.presenter?.failedToRetrieveGenres(error)
        })
    }
}
